# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bilet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forname', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('opisanie', models.TextField()),
                ('dlitelnost', models.FloatField()),
                ('proizvodstvo', models.CharField(max_length=20)),
                ('rezhiser', models.CharField(max_length=20)),
                ('actors', models.TextField()),
                ('year', models.IntegerField()),
                ('image', models.ImageField(upload_to='static/img')),
                ('trailer', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Seans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('price', models.CommaSeparatedIntegerField(max_length=15)),
                ('film', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='films.Film')),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kol_bil', models.IntegerField()),
                ('summa', models.IntegerField()),
                ('seans_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='films.Seans')),
            ],
        ),
        migrations.CreateModel(
            name='Zhanr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='zhanr',
            field=models.ManyToManyField(to='films.Zhanr'),
        ),
        migrations.AddField(
            model_name='bron',
            name='seans_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='films.Seans'),
        ),
        migrations.AddField(
            model_name='bilet',
            name='seans_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='films.Seans'),
        ),
    ]
