# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 14:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_auto_20160413_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='format',
            field=models.CharField(default=datetime.datetime(2016, 4, 14, 14, 6, 12, 350500, tzinfo=utc), max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(upload_to='static/films'),
        ),
        migrations.AlterField(
            model_name='film',
            name='rezhiser',
            field=models.CharField(max_length=50),
        ),
    ]
