# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_film_secondname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(height_field='525', upload_to='static/films', width_field='260'),
        ),
    ]
