# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 15:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_auto_20160414_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='prokat',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 4, 14, 15, 43, 29, 222300, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
