# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 12:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_auto_20160420_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='url_name',
            field=models.CharField(default=datetime.datetime(2016, 4, 20, 12, 25, 1, 197700, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(height_field='image_height', upload_to='media/films', width_field='image_width'),
        ),
    ]
