# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0011_auto_20160420_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bilet',
            name='number',
        ),
        migrations.RemoveField(
            model_name='bron',
            name='number',
        ),
        migrations.AddField(
            model_name='bilet',
            name='row',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bilet',
            name='seat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bron',
            name='row',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bron',
            name='seat',
            field=models.IntegerField(default=0),
        ),
    ]
