# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0012_auto_20160504_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilet',
            name='free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bron',
            name='free',
            field=models.BooleanField(default=True),
        ),
    ]
