# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0013_auto_20160508_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bilet',
            name='free',
        ),
        migrations.RemoveField(
            model_name='bron',
            name='free',
        ),
    ]
