# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0014_auto_20160510_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilet',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bron',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
