# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0015_auto_20160521_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='kol_bil',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sell',
            name='summa',
            field=models.IntegerField(default=0),
        ),
    ]
