# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import films.models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0012_auto_20160504_1831'),
        ('kinouser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kinouser',
            name='bilets',
            field=models.ForeignKey(default=0, on_delete=films.models.Bron, to='films.Bilet'),
        ),
    ]
