# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0012_auto_20160504_1831'),
        ('kinouser', '0002_kinouser_bilets'),
    ]

    operations = [
        migrations.AddField(
            model_name='kinouser',
            name='bron',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='films.Bron'),
        ),
        migrations.AlterField(
            model_name='kinouser',
            name='bilets',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='films.Bilet'),
        ),
    ]
