# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0014_auto_20160510_1811'),
        ('kinouser', '0003_auto_20160508_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kinouser',
            name='bilets',
        ),
        migrations.AddField(
            model_name='kinouser',
            name='bilets',
            field=models.ManyToManyField(default=0, to='films.Bilet'),
        ),
        migrations.RemoveField(
            model_name='kinouser',
            name='bron',
        ),
        migrations.AddField(
            model_name='kinouser',
            name='bron',
            field=models.ManyToManyField(default=0, to='films.Bron'),
        ),
    ]
