# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinouser', '0004_auto_20160510_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='kinouser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Is staff user'),
        ),
    ]
