# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 13:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('otziv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otziv',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 5, 16, 13, 31, 41, 323996, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otziv',
            name='text',
            field=models.TextField(max_length=20000),
        ),
    ]
